### ISSUE TITLE
Robotic Sounding Voice Problem

### ISSUE THREAD

**Issue by dxcode** [alexbw/novocaine#112]
Hi guys!

I'm trying to get the perfect chipmunk voice - like the one in the TLC.mp3 Novocaine preview - I'm reading / playing back from a prerecorded file.

But all I get is a robotic voice with weird / almost no pitch alteration.

Does anyone have a good example how to achieve a good chipmunk voice?

Thank you very much!

**Comment by dxcode** [comment]
Anyone? Please

**Comment by alexbw** [comment]
Hey, the purpose of Novocaine is to work with raw audio. Unfortunately, producing audio effects, like robot voices, is out of the scope of this project. If you are looking to do time- or frequency-stretching like making chipmunk voices on a live production system, I would recommend this: http://www.zynaptiq.com/ztx/. I have used it in a previous gig. I'm not sure how much the license costs anymore.

I'm going to close this issue, because this isn't about a core feature of Novocaine.
