### ISSUE TITLE
Getting couldn't render output unit -50 for cases using audio in

### ISSUE THREAD

**Issue by tkirke** [alexbw/novocaine#27]
Device is fine but simulator always gives this error. Tried on Xcode 4.3 and 4.4 and on different MacBooks. Anyone else see this?

**Comment by sb8244** [comment]
Still an issue with recording block on a latest osx + iphone 6 simulator. Happened the first time in several weeks. Restart doesn't help.

**Comment by technace2015** [comment]
I found one problem in audio processing. In simulator it's works fine but problem in iOS devices.

Audio File :https://www.dropbox.com/s/1eybs11wog8v3rz/Policemen%20%26%20Pirates.mp3?dl=0 

After 5 second there is guitar sound for 4-5 seconds. That guitar sound missing in iOS device.

If any one help me then it would be great.

Thanks in advance.

**Comment by ahaith** [comment]
I just encountered a similar problem with both an iPhone 6S and a new iPad mini. In this case iNumberFrames was occasionally 236, and forcing it to 235 solved the problem.

**Comment by technace2015** [comment]
ThanksI'll try and let you know.---- On Mon, 16 May 2016 08:24:38 -0400  Andy Haith<notifications@github.com> wrote ----I just encountered a similar problem with both an iPhone 6S and a new iPad mini. In this case iNumberFrames was occasionally 236, and forcing it to 235 solved the problem.  —You are receiving this because you commented.Reply to this email directly or view it on GitHub
