### ISSUE TITLE
Unable to play a .wav file using the sample...

### ISSUE THREAD

**Issue by ezrover** [alexbw/novocaine#42]
Hi Alex, would you know why .wav files wont play on this example? Which parameters do I need to change/tweak to make it play? The wav file is sample rate: 11025, bits per sample: 8, channels: 1

**Comment by alexbird** [comment]
I ended up reading this thread because I need to read uncompressed data into a unit test fixture. The sounds are actually encoded data, so I really don't want to apply lossy compression. Also this is test code, so the performance on the iPhone isn't relevant. I just want to load data as if it was a buffer from setInputData, so I can test how it is handled. 
I'm not demanding anyone adds support for that, just pointing out that it is a valid use case!
